services:
  frontend:
    build:
      context: ./frontend/chess-coach-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - chess-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      # - DATABASE_URL=postgresql://postgres:postgres@db:5432/chess_coach
      - AI_ENGINE_URL=http://ai-engine:5000
    depends_on:
      - db
      - ai-engine
    networks:
      - chess-network
    restart: unless-stopped
    env_file:
      - .env

  ai-engine:
    build:
      context: ./ai-engine
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - MODEL_PATH=/app/models
    volumes:
      - ai-models:/app/models
    networks:
      - chess-network
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chess_coach
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - chess-network
    restart: unless-stopped

networks:
  chess-network:
    driver: bridge

volumes:
  postgres-data:
  ai-models: 