services:
  frontend:
    build:
      context: ./frontend/chess-coach-frontend/client
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost:8000}
        - VITE_REACT_APP_SUPABASE_URL=${SUPABASE_URL}
        - VITE_REACT_APP_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    ports:
      - "3000:80"
    networks:
      - chess-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AI_ENGINE_URL=http://ai-engine:5000
    depends_on:
      - ai-engine
    networks:
      - chess-network

  ai-engine:
    build:
      context: ./ai-engine
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MODEL_PATH=/app/models/chess_model.pkl
    volumes:
      - ./ai-engine/models:/app/models
    networks:
      - chess-network

networks:
  chess-network:
    driver: bridge 